2022-04-08 13:44:44.235 wdl.w:hworld_workflow NOTICE workflow start :: name: "hworld_workflow", source: "/home/kevin_libuit/wm_training/wdl/workflows/wf_hworld.wdl", line: 6, column: 1, dir: "/home/kevin_libuit/wm_training/wdl/data/hwrold/20220408_134444_hworld_workflow"
2022-04-08 13:44:44.587 wdl.w:hworld_workflow NOTICE miniwdl :: version: "v1.1.3"
2022-04-08 13:44:44.635 wdl.w:hworld_workflow NOTICE issue :: job: "call-hworld_task", callee: "hworld_task"
2022-04-08 13:44:44.637 wdl.w:hworld_workflow.t:call-hworld_task NOTICE task start :: name: "hworld_task", source: "../tasks/task_hworld.wdl", line: 3, column: 1, dir: "/home/kevin_libuit/wm_training/wdl/data/hwrold/20220408_134444_hworld_workflow/call-hworld_task", thread: 140673152214784
2022-04-08 13:44:44.814 wdl.w:hworld_workflow.t:call-hworld_task WARNING docker swarm lists existing miniwdl-related services. This is normal if other miniwdl processes are running concurrently; otherwise, stale state could interfere with this run. To reset it, `docker swarm leave --force`
2022-04-08 13:44:44.815 wdl.w:hworld_workflow.t:call-hworld_task NOTICE docker swarm resources :: workers: 1, max_cpus: 8, max_mem_bytes: 33668861952, total_cpus: 8, total_mem_bytes: 33668861952
2022-04-08 13:44:44.817 wdl.w:hworld_workflow.t:call-hworld_task WARNING ignored runtime settings :: keys: ["disks"]
2022-04-08 13:45:04.481 wdl.w:hworld_workflow.t:call-hworld_task NOTICE docker image :: tag: "quay.io/theiagen/utility:1.2", id: "sha256:cc42a01fdb6240a6f9012e923014ce0129bab5c2dac7cd16fb90edab96a49333", RepoDigest: "quay.io/theiagen/utility@sha256:8d39c5018411b2cc243ff354754963a3a595c114be4c450372eab9961f4f2170"
2022-04-08 13:45:17.385 wdl.w:hworld_workflow.t:call-hworld_task NOTICE docker task exit :: state: "complete", exit_code: 0
2022-04-08 13:45:18.193 wdl.w:hworld_workflow.t:call-hworld_task WARNING output path not found in container (error unless declared type is optional) :: output: "hworld_results", path: "message2world"
2022-04-08 13:45:18.194 wdl.w:hworld_workflow.t:call-hworld_task ERROR task hworld_task (../tasks/task_hworld.wdl Ln 3 Col 1) failed :: dir: "/home/kevin_libuit/wm_training/wdl/data/hwrold/20220408_134444_hworld_workflow/call-hworld_task", error: "OutputError", message: "File/Directory path not found in task output hworld_results", node: "decl-hworld_results"
2022-04-08 13:45:18.196 wdl.w:hworld_workflow ERROR call failure propagating :: from: "call-hworld_task", dir: "/home/kevin_libuit/wm_training/wdl/data/hwrold/20220408_134444_hworld_workflow"
2022-04-08 13:45:18.197 wdl.w:hworld_workflow NOTICE aborting workflow
